print("Hello World")
print("Hello Again")
print("Hello, Shekhar")
print("This is Fun")
print("Yay! Printing")
print("*************************")
print(">>>>>>>>><<<<<<<<<<<<<<")
print(10 * 'h')
print(20 * '#')
